### ISSUE TITLE
Additional stats

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/status-fs-neo-org#42]
... :writing_hand: WIP

Inspired by siastats.info

- [ ] [Total number of storage nodes (in map section)](https://github.com/nspcc-dev/neofs-web-stat/issues/44)
- [ ] Used storage
- [ ] Graph of used storage (issues with estimations)
```go
	ctx := context.Background()
	pk, err := keys.NewPrivateKey()
	exitErr(err)
	cli, err := client.New(pk, "wss://rpc01.morph.testnet.fs.neo.org:51331/ws", client.WithContext(ctx))
	exitErr(err)
	cnr, err := util.Uint160DecodeStringLE("9dbd2b5e67568ed285c3d6f96bac4edf5e1efba0")
	exitErr(err)
	cnrClient, err := cntClient.NewFromMorph(cli, cnr, 0)
	exitErr(err)
	list, err := cnrClient.ListLoadEstimationsByEpoch(6438)
	exitErr(err)
	total := uint64(0)
	for i := range list {
		est, err := cnrClient.GetUsedSpaceEstimations(list[i])
		exitErr(err)
		for j := range est.Values {
			sz := est.Values[j].Size
			total += sz
			fmt.Println(sz, est.ContainerID.String())
		}
	}
	fmt.Println(total)
```
- [ ] Deposited GAS
- [ ] Basic Storage pricing per GiB without audit
- [ ] Storage pricing per GiB with audit (calculate average price of nodes)
- [ ] <s>Host monitor with details: IP, locodes, etc.</s>
- [ ] <s>Capacity</s>
- [ ] Outage (number of node exits from network map)
- [ ] Side chain monitor: blocks, transactions
- [ ] <s>Profitability</s>
